shyft_grpc:
  url: "https://grpc.ny.shyft.to"
  x_token: "1234"

shyft_rpc:
  url: "https://api.shyft.to"
  api_key: "1234"
  network: "devnet"

wallet:
  private_key: "your_solana_private_key_here"
  public_key: "your_solana_public_key_here"